# ================================
# BTC 5m LSTM Trading Configuration
# สำหรับการเทรนและใช้งานจริง
# ================================
#
# การใช้งาน:
# - สำหรับการทดสอบ: ลด train_months, max_epochs, batch_size
# - สำหรับการเทรนจริง: ใช้ค่าปัจจุบัน
# - สำหรับ CPU: เปลี่ยน device เป็น "cpu" และลด batch_size
#
# ================================
# การตั้งค่าข้อมูล (Data Configuration)
# ================================
data:
  raw_glob: "data/raw/*.*"     # ไฟล์ข้อมูลดิบ รองรับ .csv หรือ .parquet
  tz_source: "Asia/Bangkok"    # timezone ของข้อมูลต้นฉบับ (เปลี่ยนตามต้องการ)
  tz_target: "UTC"             # แปลงเป็น UTC สำหรับการประมวลผลภายใน
  ensure_regular_5m: true      # เติมช่องว่างให้ข้อมูลเป็น 5 นาทีสม่ำเสมอ

# ================================
# การสร้างฟีเจอร์ (Feature Engineering)
# ================================
feature:
  rsi_period: 14                         # ช่วงเวลาการคำนวณ RSI (Relative Strength Index)
  ema_periods: [20, 50, 200]            # ช่วงเวลา EMA (Exponential Moving Average) หลายเส้น
  atr_period: 14                         # ช่วงเวลาการคำนวณ ATR (Average True Range)
  return_lags: [1,3,6,12,24,48,96]      # ระยะย้อนหลังของ log return (1=5นาที, 96=8ชั่วโมง)

# ================================
# การติดป้ายข้อมูล (Labeling)
# ================================
label:
  atr_mult_tp: 2.5      # ตัวคูณ ATR สำหรับ Take Profit (กำไร = 2.5 x ATR)
  atr_mult_sl: 1.6      # ตัวคูณ ATR สำหรับ Stop Loss (ขาดทุน = 1.6 x ATR)
  max_holding: 36       # ระยะเวลาถือครองสูงสุด (36 periods = 3 ชั่วโมง)
  min_move_bps: 5       # การเคลื่อนไหวขั้นต่ำที่ถือว่าเป็นสัญญาณ (5 basis points = 0.05%)

# ================================
# การแบ่งข้อมูล (Data Splitting)
# ================================
split:
  train_months: 12      # ใช้ข้อมูล 12 เดือนสำหรับการเทรนโมเดล (ลดเป็น 3-6 สำหรับการทดสอบ)
  valid_months: 3       # ใช้ข้อมูล 3 เดือนสำหรับการ validation (ลดเป็น 1 สำหรับการทดสอบ)
  test_months: 3        # ใช้ข้อมูล 3 เดือนสำหรับการทดสอบ/เทรด (ลดเป็น 1 สำหรับการทดสอบ)
  step_months: 3        # เลื่อนหน้าต่างข้อมูลทุก 3 เดือน (Walk-Forward)

# ================================
# การเทรนโมเดล (Model Training)
# ================================
train:
  seq_len: 96                     # ความยาวของ sequence สำหรับ LSTM (96 = 8 ชั่วโมง)
  batch_size: 1024               # จำนวนตัวอย่างใน batch หนึ่ง (ลดเป็น 256-512 หาก GPU memory ไม่พอ)
  lr: 0.001                       # Learning rate (อัตราการเรียนรู้)
  max_epochs: 25                 # จำนวน epoch สูงสุด (ลดเป็น 5-10 สำหรับการทดสอบ)
  early_stop_patience: 5         # หยุดการเทรนหากไม่มีการปรับปรุงใน 5 epochs
  class_weights: [1.0, 0.6, 1.0] # น้ำหนักของแต่ละคลาส [-1=Short, 0=Neutral, +1=Long]
  device: "cuda"                 # ใช้ GPU ("cuda") หรือ CPU ("cpu") - เปลี่ยนเป็น "cpu" หากไม่มี GPU

# ================================
# การตั้งค่าการเทรด (Trading Configuration)
# ================================
trade:
  proba_threshold: 0.60   # เกณฑ์ความมั่นใจขั้นต่ำในการเปิดออเดอร์ (60% - เพิ่มขึ้นเพื่อความระมัดระวัง)
  fee_bps: 5             # ค่าธรรมเนียมการเทรด (5 basis points = 0.05%)
  slippage_bps: 2        # Slippage ที่คาดหวัง (2 basis points = 0.02%)
  atr_mult_tp: 2.5       # ตัวคูณ ATR สำหรับ Take Profit
  atr_mult_sl: 1.6       # ตัวคูณ ATR สำหรับ Stop Loss
  max_holding: 36        # ระยะเวลาถือครองสูงสุดต่อออเดอร์ (36 periods = 3 ชั่วโมง)

# ================================
# คำแนะนำการใช้งาน:
# 
# การทดสอบเร็ว:
# - train_months: 3, valid_months: 1, test_months: 1
# - max_epochs: 5, batch_size: 256, device: "cpu"
#
# การเทรนจริง:
# - ใช้ค่าปัจจุบัน (แนะนำ GPU)
# - ตรวจสอบ GPU memory หาก batch_size ใหญ่เกินไป
#
# รันคำสั่ง:
# python -m scripts.run_train
# ================================
